name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: |
        rsync -av ./ /root/ros2_ws/src/network_usage/
        cd /root/ros2_ws
        sudo rosdep fix-permissions
        rosdep update
        sudo apt-get install -y ros-foxy-launch-ros
        rosdep install -i --from-path src --ignore-src -r -y --rosdistro foxy
        bash -xv ./src/network_usage/test/test.bash /root
